import type { Entry } from '../db'
import type { Profile } from '../db'
import { parseDate, weekdayName, monthName } from './dateUtils'

const WEEKDAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']

function groupByWeek(entries: Entry[]): Map<number, Entry[]> {
  const map = new Map<number, Entry[]>()
  for (const e of entries) {
    const list = map.get(e.weekNumber) ?? []
    list.push(e)
    map.set(e.weekNumber, list)
  }
  return map
}

export function exportPlainText(entries: Entry[], profile: Profile, label: string): string {
  const lines: string[] = []
  lines.push(`FEDERAL UNIVERSITY OF TECHNOLOGY, OWERRI`)
  lines.push(`STUDENTS INDUSTRIAL WORK EXPERIENCE SCHEME (SIWES)`)
  lines.push(``)
  lines.push(`Name: ${profile.name}    Matric No: ${profile.matricNo}`)
  lines.push(`Department: ${profile.department}    Institution: ${profile.institution}`)
  lines.push(`Organization: ${profile.organization}    Supervisor: ${profile.supervisor}`)
  lines.push(`Period: ${label}`)
  lines.push(`${'─'.repeat(60)}`)
  lines.push(``)

  const byWeek = groupByWeek(entries)
  const weeks = Array.from(byWeek.keys()).sort((a, b) => a - b)

  for (const wk of weeks) {
    const wkEntries = byWeek.get(wk)!
    lines.push(`WEEK ${wk}`)
    for (const day of WEEKDAYS) {
      const entry = wkEntries.find(e => weekdayName(e.date).toUpperCase() === day.toUpperCase())
      lines.push(`${day.padEnd(12)} ${entry?.summary ?? '—'}`)
    }
    lines.push(``)
  }

  return lines.join('\n')
}

export async function exportPDF(entries: Entry[], profile: Profile, label: string): Promise<void> {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  const pink  = [255, 45, 120] as const
  const black = [13, 13, 13]   as const
  const gray  = [100, 100, 100] as const

  let y = 20

  // Header
  doc.setFillColor(...pink)
  doc.rect(0, 0, 210, 14, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text('LOGGER — SIWES DAILY LOGBOOK', 105, 9, { align: 'center' })

  y = 22
  doc.setTextColor(...black)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text('FEDERAL UNIVERSITY OF TECHNOLOGY, OWERRI', 105, y, { align: 'center' })
  y += 6
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text('Students Industrial Work Experience Scheme (SIWES)', 105, y, { align: 'center' })

  y += 8
  doc.setDrawColor(...pink)
  doc.setLineWidth(0.4)
  doc.line(14, y, 196, y)
  y += 6

  // Profile block
  doc.setFontSize(8.5)
  doc.setTextColor(...gray)
  const profileLines = [
    `Name: ${profile.name}    •    Matric No: ${profile.matricNo}`,
    `Department: ${profile.department}    •    Institution: ${profile.institution}`,
    `Organization: ${profile.organization}    •    Supervisor: ${profile.supervisor}`,
    `Period: ${label}`,
  ]
  for (const line of profileLines) {
    doc.text(line, 14, y)
    y += 5
  }

  y += 4
  doc.setDrawColor(...pink)
  doc.line(14, y, 196, y)
  y += 8

  const byWeek = groupByWeek(entries)
  const weeks = Array.from(byWeek.keys()).sort((a, b) => a - b)

  for (const wk of weeks) {
    if (y > 260) { doc.addPage(); y = 20 }

    // Week header
    doc.setFillColor(255, 228, 239)
    doc.rect(14, y - 4, 182, 7, 'F')
    doc.setTextColor(...pink)
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.text(`SECTION IV — STUDENT'S DAILY RECORD OF ACTIVITIES`, 15, y)
    doc.text(`WEEK ${wk}`, 193, y, { align: 'right' })
    y += 8

    const wkEntries = byWeek.get(wk)!
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8.5)

    for (const day of WEEKDAYS) {
      if (y > 270) { doc.addPage(); y = 20 }
      const entry = wkEntries.find(e => weekdayName(e.date).toUpperCase() === day.toUpperCase())
      doc.setTextColor(...black)
      doc.setFont('helvetica', 'bold')
      doc.text(`${day}:`, 14, y)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(40, 40, 40)
      const text = entry?.summary ?? '—'
      const wrapped = doc.splitTextToSize(text, 155)
      doc.text(wrapped, 40, y)
      y += wrapped.length * 5 + 2

      doc.setDrawColor(230, 230, 230)
      doc.setLineWidth(0.2)
      doc.line(14, y - 1, 196, y - 1)
    }

    y += 6
  }

  // Footer
  doc.setFontSize(7)
  doc.setTextColor(...gray)
  const totalPages = (doc as any).internal.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    doc.text(`Generated by Logger • ${new Date().toLocaleDateString('en-NG')} • Page ${i} of ${totalPages}`, 105, 290, { align: 'center' })
  }

  doc.save(`SIWES-Logbook-${label.replace(/\s/g, '-')}.pdf`)
}
